### ISSUE TITLE
Warning from ``jupyter_backend`` input should be solved

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-tools-visualization-interface#134]
See screenshot:

![image](https://github.com/user-attachments/assets/7aaebace-78ca-4fd8-9285-2a4edb7dd0e3)

If I try running locally this example, I always get this error. This is a minimum viable example - it is also happening with other libraries consuming this package. We should fix it ASAP @AlejandroFernandezLuces 

```python
import pyvista as pv

from ansys.tools.visualization_interface import Plotter

mesh = pv.Cube()

# Create a plotter
pl = Plotter()

# Add the mesh to the plotter
pl.plot(mesh)

# Show the plotter
pl.show()
```

**Comment by AlejandroFernandezLuces** [comment]
Closed by #135
