### ISSUE TITLE
Trame greatly increases loading time

### ISSUE THREAD

**Issue by AlejandroFernandezLuces** [ansys/ansys-tools-visualization-interface#162]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Loading trame greatly increases the amount of time that the library or any of its consumers takes to load. See https://github.com/ansys/pymapdl/pull/3460#issuecomment-2397017595 . We can fix this by:
- [ ] Optionally importing trame or not.
- [ ] Making lazy imports for trame related functionality.

### 📝 Steps to reproduce

Import the library

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
n/a
```

**Comment by RobPasMue** [comment]
We should definitely work on this - I also noticed it on my side
