### ISSUE TITLE
Picking only works if show() is called with a plottable object

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-tools-visualization-interface#173]
This modification will let it work as well for the default use cases where show is called "empty", no input args:

![image](https://github.com/user-attachments/assets/33ac3cae-b7f4-4af3-a542-bf2cd398c67a)

Simple modification right at the end to return the picked list.... I'm not sure why we are doing the previous checks honestly... they don't make much sense to me.

**Comment by MaxJPRey** [comment]
Might be worth adding a comment before the `if/elif` statement.

**Comment by RobPasMue** [comment]
Agreed
