### ISSUE TITLE
Fix User Guide - Use with PyVista meshes code snippet

### ISSUE THREAD

**Issue by PProfizi** [ansys/ansys-tools-visualization-interface#41]
### Description of the modifications

In the last line of the code snippet for the `Use with PyVista meshes` section:

replace `pl.add()` with `pl.show()`

### Useful links and references

https://visualization-interface.tools.docs.pyansys.com/version/stable/user_guide/index.html#use-with-pyvista-meshes

**Comment by AlejandroFernandezLuces** [comment]
Closed by #61 , thanks for opening the issue @PProfizi 🙂
