### ISSUE TITLE
Documentation landing page cards wrongly formatted

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-tools-visualization-interface#54]
![image](https://github.com/ansys/ansys-tools-visualization-interface/assets/37798125/38a989a9-c725-411d-9665-e0887ea64863)

Remove second hyperlink since it is not needed

**Comment by RobPasMue** [comment]
This is fixed via the ansys-sphinx-theme --> Closing

Release is needed (fix is in dev right now). Pinging @AlejandroFernandezLuces

**Comment by AlejandroFernandezLuces** [comment]
Release done 🙂

**Comment by RobPasMue** [comment]
Thanks @AlejandroFernandezLuces!
