### ISSUE TITLE
Online docs claim to have PDF available but download fails

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-tools-visualization-interface#67]
I guess we are not uploading the PDF as part of the docs build. This should be automated by https://github.com/ansys/actions/pull/467 but it seems like it has staled.... @SMoraisAnsys what's the status in that PR?

![image](https://github.com/ansys/ansys-tools-visualization-interface/assets/37798125/b6ed15e8-f57b-4e74-8e65-83c68c84882a)

We should try and fix it anyway - either wait for the PR to be merged or do it manually.

**Comment by SMoraisAnsys** [comment]
I think I managed to obtain something working but wanted to:
- clean things a bit;
- use the approach shown by Jorge about running script in github environment.

I can try to allocate time tomorrow to finish this !
