### ISSUE TITLE
Warnings being thrown in the examples

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-tools-visualization-interface#74]
See https://visualization-interface.tools.docs.pyansys.com/version/dev/examples/00-basic-pyvista-examples/plain_usage.html

The following warnings appear. We should try to fix them or silence them. Ideally fix them...

![image](https://github.com/ansys/ansys-tools-visualization-interface/assets/37798125/9d2dcfba-2c2d-46fc-a12c-21a54801a10c)

**Comment by AlejandroFernandezLuces** [comment]
Fixed by #92 , using the `jupyter_backend` parameter is not needed anymore, since we only can use `trame`. The other alternatives (`client` and `server`) are just configurations of the trame backend.
